server:
  port: 8103
management:
  endpoints:
    web:
      exposure:
        include: health  # 이 부분 추가
custom:
  prod:
    cookieDomain: pawpaw.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "pawpaw"
    cookieDomain: "${custom.prod.cookieDomain}"
    meilisearchUrl: "http://43.203.126.129:7700"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
